### PR TITLE
Set the ha and autopoweron options while creating vms

### LINKED ISSUE #209: `high_availability` and `auto_poweron` settings don't seem to apply on create
Using this Terraform config
```hcl
resource "xenorchestra_vm" "vm" {
  name_label = "${local.projekt}"
  template   = data.xenorchestra_template.template.id

  cpus       = 1
  memory_max = 1 * local.gib

  auto_poweron      = true
  high_availability = "restart"

  wait_for_ip = true

  cdrom {
    id = data.xenorchestra_vdi.iso.id
  }

  network {
    network_id = data.xenorchestra_network.network.id
  }

  disk {
    sr_id      = data.xenorchestra_sr.storage.id
    name_label = "Data disk for ${local.projekt}"
    size       = 1 * local.gib
  }

  tags = [
    "dev",
  ]
}
```

* run apply
* Check in XOA what ha and autopoweron is set to
  auto_poweron is false
  high_availability is disabled
* run apply again

Terraform confirms that they are disabled but should be enabled

```shell 
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # xenorchestra_vm.vm will be updated in-place
  ~ resource "xenorchestra_vm" "vm" {
      ~ auto_poweron       = false -> true
      + high_availability  = "restart"
        id                 = "0fb977c1-a761-4b6e-74c5-1ae1c08f8bfc"
        tags               = [
            "dev",
        ]
        # (17 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

* Check in XOA what ha and autopoweron are set to
  auto_poweron is now true
  high_availability is now 'restart'
* another apply now reports that everything matches
```shell

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### PR DESCRIPTION
**Pull request by 4censord**
This fixes  #209

### CODE REVIEW

**Comment by ddelnano** [comment]
@4censord apologies for the late reply! I'm planning to be more active in the project and appreciate your contribution.

I'm currently working on getting a CI job setup to make reviewing these easier (running the test suite is very painful and time consuming at the moment). So I'll be giving this a review soon (in the next week).

**Comment by 4censord** [comment]
It seem to not have been caught by the tests that this was broken, should we add a new test to check that it is working now?

**Comment by ddelnano** [comment]
@4censord validating this functionality with a test would be great. We already have the [TestAccXenorchestraVm_updatesWithoutReboot test](https://github.com/terra-farm/terraform-provider-xenorchestra/blob/9772a30c79e1dbce2868b4330fea6bb448bdc64f/xoa/resource_xenorchestra_vm_test.go#L1146), which would be a good fit for verifying this functionality.

Can you update this PR to include that?

**Comment by 4censord** [comment]
I am unsure whether this is actually the right test to use for this. 
The issue did only surface on the initial creation set, but this tests if modifications work.

We could change the test so that it creates the vm with ha and autopoweron and later removes those. But i'm not sure if that's the right course.

**Comment by 4censord** [comment]
Do we have a test that creates a vm with all parameters set to non default values?
That would be the ideal place for this imo.

**Comment by ddelnano** [comment]
> I am unsure whether this is actually the right test to use for this.
The issue did only surface on the initial creation set, but this tests if modifications work.

Sorry, I misunderstood where the discrepancy was.

We don't have a test that sets all parameters to non default values. That works or we can create a more specific test for these settings in the short term. I think doing that makes it easier to determine what the failure is if a test fails, but either approach works.

**Comment by ryanlelek** [comment]
This commit is small and looks good to me.
Is there any specific testing you'd like me to do to be more comfortable merging this?

**Comment by 4censord** [comment]
What is missing now is a test to verify that this works.

Basicaly creating a vm with both parameters set, and check that they are set after the fist apply.

If you'd like to add this, please feel free.

I currently have neither the time, nor motivation, nor a cluster for running the tests on.

**Comment by sboyd-m** [comment]
I was able to test this, and it does indeed set autopoweron and HA. Would really advocate this being merged, as it is an annoyance for us as well.

**Comment by ddelnano** [comment]
I'll be able to pick up adding a test for this in the upcoming days. One example for why I believe adding a test is a crucial and necessary step, is that the XO api client layer needs to be significantly reworked due to the breaking change made by the XO APi (details in #238 and linked issues). Without this test, I think it's likely that a small fix like this will be broken during that large refactor.

I understand this functionality is important and that this has been an annoyance, but this fix should be coming soon.

**Comment by ddelnano** [comment]
The test changes ended up being easy to fix (#252). Reordering which changes are applied first ensures that the creation with a non default value is covered.

**Pull request closed without merging**
