### PR TITLE
Remove unneeded throw panic

### PR DESCRIPTION
**Pull request by ravager-dk**
Fix for issue #232. Remove the panic thrown by having an unknown value from a separate resource. The unformattedMac is instead returned in this case. Validation still prevents using unparseble strings as mac address.

### CODE REVIEW

**Comment by VirtualDisk** [comment]
Any update on this getting merged?

**Comment by ddelnano** [comment]
I would like to understand how this will be accomplished in the new provider framework (as discussed [here](https://github.com/terra-farm/terraform-provider-xenorchestra/issues/232#issuecomment-1493948493)). I'm hesitant to accept a breaking change without understanding how it will be addressed in the longer term.

I unfortunately haven't had time to do that research myself since I've been traveling a lot the past month.

**Comment by ravager-dk** [comment]
Any updates to this? The new provider framework is not needed at the moment, and awaiting to fix issues until a complete code rewrite is done for the framework seems to me at least unnecessary. With the new Terraform license terms, not even sure we should move beyond current SDK until opentofu becomes standard.
So I still suggest merging this PR.

**Comment by ddelnano** [comment]
@ravager-dk sorry for failing to follow up on this. I haven't spent regular time on the provider for a few months, but from this month forward I will be back on a regular schedule.

I'm currently focusing on setting up a CI build, but next week I will circle back to this.

**Pull request closed without merging**
