### PR TITLE
Rebased upstream xo sdk

### PR DESCRIPTION
**Pull request by ddelnano**
This is a rebased version of #174 due to #175.  It was tested locally with https://github.com/vatesfr/xo-sdk-go/pull/4.

## Todo
- [x] Update `go.mod` file once https://github.com/vatesfr/xo-sdk-go/pull/4 is merged

### CODE REVIEW

**Comment by ddelnano** [comment]
@ringods sorry that your change was made just as I needed to revert some code in the xo client. Please see the related review, but it's probably easiest for us to use this branch (since yours needed a rebase).

**Comment by ringods** [comment]
@ddelnano no problem. I just approved and merged your PR in the XO sdk repo.

**Comment by ddelnano** [comment]
I'll run the terraform acceptance tests once more to verify this is good and then I'll merge this.

**Comment by ddelnano** [comment]
Closing this due to the conversation on https://github.com/vatesfr/xo-sdk-go/pull/5. I'll happily revisit it and upstream changes there if need be.

**Pull request closed without merging**
